//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devoctomy.cachy.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("devoctomy.cachy.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hitmail.com
        ///rxdoc.biz
        ///cox.com
        ///126.net
        ///126.com
        ///comast.com
        ///comast.net
        ///yandex.com
        ///wegas.ru
        ///twc.com
        ///icloud.com
        ///charter.com
        ///outlook.com
        ///gmx.com
        ///.ddns.org
        ///.findhere.com
        ///.freeservers.com
        ///.zzn.com
        ///1033edge.com
        ///11mail.com
        ///123.com
        ///123box.net
        ///123india.com
        ///123mail.cl
        ///123qwe.co.uk
        ///150ml.com
        ///15meg4free.com
        ///163.com
        ///1coolplace.com
        ///1freeemail.com
        ///1funplace.com
        ///1internetdrive.com
        ///1mail.net
        ///1me.net
        ///1mum.com
        ///1musicrow.com
        ///1netdrive.com
        ///1nsyncfan.com
        ///1under.com
        ///1webave.com
        ///1webhighway.com
        ///212.com
        ///24horas.com
        ///2911.net
        ///2bmail.co. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string domains {
            get {
                return ResourceManager.GetString("domains", resourceCulture);
            }
        }
    }
}
